---
title: "Readin_Textgrids"
author: "Jason Geller"
date: "1/17/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message=FALSE,
                      warning=FALSE)
```


```{r packages}
install.package("phonfieldwork")
library(tidyverse)
library(rPraat)
library(here)
library(phonfieldwork)

```


```{r textgrids}

inputFolder <- here::here("textgrids")

listFiles <- list.files(path = inputFolder, pattern = "\\.TextGrid$" , ignore.case = TRUE)

x <- list() # store textgrids as a list for each P

for (I in seq_along(listFiles)) {
    file <- listFiles[I]
    fileName <- substr(file, 1, nchar(file) - nchar(".TextGrid"))

    fileTextGrid <- paste0(inputFolder, "/", fileName, ".TextGrid")
    # filePitchTier <- paste0(inputFolder, "/", fileName, ".PitchTier")
    # filePitch <- paste0(inputFolder, "/", fileName, ".Pitch")
    # fileIntensityTier <- paste0(inputFolder, "/", fileName, ".IntensityTier")
    # fileFormant <- paste0(inputFolder, "/", fileName, ".Formant")
    # fileSound <- paste0(inputFolder, "/", fileName, ".wav")
    # fileCollection <- paste0(inputFolder, "/", fileName, ".Collection")

     x[[paste0("elemnet", file)]] <- textgrid_to_df(fileTextGrid)
    # pt <- pt.read(filePitchTier)
    # pitch <- pt.read(filePitch)
    # it <- it.read(fileIntensityTier)
    # formant <- formant.read(fileFormant)
    # snd <- snd.read(fileSound)
    # col <- col.read(fileCollection)
    # ...

    # ... process tg, pt, pitch, it, formant, snd, col...
}


#x
```
# Unlist
```{r}

library(data.table)

# capital is noun, appears adjectives are colors
# just look at noun focus trials

# dv is intensity
# participant level 1
# item is level 2
# random slope of typicality
# fixed effects of typicality

text_unlist <- rbindlist(x)

head(text_unlist)

```
